import { formatDate } from '@/utills/utills'
import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home({ blogs }) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Amrytt Pvt. Ltd. | Task</title>
        <meta name='description' content='Generated by Amrytt Pvt. Ltd. | Task' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <section className='blog-list container'>
          <h1 className='section-title'>
            <span>Our Latest Blogs</span>
            <button className='section-title_btn' onClick={() => router.push('/blogs')}>
              View All Blogs
            </button>
          </h1>
          <div className='blog-list_container'>
            {blogs?.data?.slice(0, 2).map((blog) => (
              <div key={blog._id} className='blog-list_blog-card'>
                <p className='blog-card_date'>{formatDate(blog?.dCreatedDate)}</p>
                <h1 className='blog-card_title'>{blog?.sTitle}</h1>
                <div className='blog-card_content' dangerouslySetInnerHTML={{ __html: blog?.sContent?.slice(0, 120) + '...' }}></div>
                <button
                  className='blog-card_read-more-btn'
                  onClick={() =>
                    router.push({
                      pathname: `/blogs/${blog.sTitle}/${blog._id}`
                    })
                  }
                >
                  Read More
                </button>
              </div>
            ))}
          </div>
        </section>
      </div>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_ENDPOINT}/blogs`)
  const blogs = await res.json()

  return {
    props: {
      blogs
    }
  }
}
